name: Build Windows (Flutter)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: shingora_web   # 👈 your project folder

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter doctor
        run: flutter doctor -v
        continue-on-error: true

      - name: Get dependencies
        run: flutter pub get

      - name: Ensure platform folders
        run: flutter create.

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-folder
          path: sound_model/build/windows/x64/runner/Release/
          path: build/windows/x64/runner/Release/
